## Verificación de supuestos

```{r}
#| label: supuestos-anova
modelo <- aov(bill_length_mm ~ species, data = df)                                  

# Normalidad de residuos
Normalidad <- shapiro.test(residuals(modelo))

# Homogeneidad de varianzas (Levene)
Homogeneidad <- leveneTest(bill_length_mm ~ species, data = df)

# Tablas
knitr::kable(
  broom::tidy(Normalidad),
  caption = "Test de normalidad de residuos (Shapiro-Wilk)"
)

knitr::kable(
  broom::tidy(Homogeneidad),
  caption = "Test de homogeneidad de varianzas (Levene)"
)

```

## Ejeccución del Kruskal-Wallis global

```{r}
#| label: kruskal_global

# Kruskal-Wallis (global)
kruskal_res <- df %>% kruskal_test(bill_length_mm ~ species)

# Formatear p-value como p < 0.001 si es muy pequeño
kruskal_res <- kruskal_res %>%
  mutate(p = ifelse(p < 0.001, "< 0.001", round(p, 3)))

knitr::kable(kruskal_res, caption = "Prueba Kruskal-Wallis global")


```
```{r}
#| label: epsilon-squared

# Tamaño de efecto (epsilon-squared)
Efe <- df %>% kruskal_effsize(bill_length_mm ~ species)
knitr::kable(Efe, caption = "Tamaño de efecto (epsilon-squared)")
```

