## Limpieza y revisión inicial de los datos

```{r}
#|label: prep
#Librerías
library(tidyverse)
library(janitor)
library(skimr)
library(palmerpenguins)

df_raw <- penguins %>% as_tibble() # guardo raw para auditoría
```

```{r}
#|label: clean_names
df <- df_raw %>% clean_names()
names(df) # comprobar
```

```{r}
#|label: skim
skim(df) #Resumen rápido (estructura + NA)
```

```{r}
#|label: duplicates
n_dup <- sum(duplicated(df))
n_dup # Número de filas duplicadas

# si quieres, ver filas duplicadas (opcional)
df %>% filter(duplicated(.)) %>% head()

# eliminar duplicados exactos (opcional)
df <- df %>% distinct()

```
```{r}
#| label: consistencia de variables categóricas

#Variables categóricas
df %>% summarise(across(where(is.character), n_distinct))
df %>% summarise(across(where(is.factor), n_distinct))
df %>% count(species)
df %>% count(island)
df %>% count(sex)

#Tipos de variables (convertir a factor si hace falta)
df <- df %>% 
  mutate(species = as.factor(species),
         island  = as.factor(island),
         sex     = as.factor(sex))

#Revisar posibles inconsistencias de texto
unique(df$species)
unique(df$island)
unique(df$sex)

df1 <- df %>% select(-year) #Eliminar columnas innecesarias
```
```{r}
#| label: ranges_boxplot variables númericas
#| fig-cap: "Rangos y valores extremos de variables morfométricas."

# Boxplots rápidos para ver rangos y "outliers" visuales
key_vars <- c("bill_length_mm","bill_depth_mm","flipper_length_mm","body_mass_g")

df %>%
  select(all_of(key_vars)) %>%
  pivot_longer(everything(), names_to = "variable", values_to = "value") %>%
  ggplot(aes(x = variable, y = value)) +
  geom_boxplot() +
  coord_flip() +
  labs(title = "Boxplots rápidos: rangos y valores extremos",
       x = "", y = "Valor") +
  theme_minimal(base_size = 13) +
  theme(
   plot.title = element_text(hjust = 0.5, face = "bold"),
   legend.position = "none",
   strip.text = element_text(face = "bold")
   )

```
