---
title: "Análisis exploratorios"
author: "Santos G"
format: pdf
editor: visual
code-overflow: wrap
toc: true
toc-depth: 2
number-sections: true
keep-tex: true
code-fold: true
code-line-numbers: true
code-tools: true
code-copy: true
echo: true
warning: false
message: false
lang: es
fig-width: 7
fig-height: 5
fig-align: center
fig-cap-location: bottom
pdf-engine: xelatex
mainfont: Times New Roman
papersize: a4
fontsize: 11pt
geometry: margin=2.5cm
---

```{r}
# Librerías 
library(tidyverse)   # Manipulación de datos: dplyr, tidyr, readr
library(janitor)     # Limpieza: clean_names(), tabyl()
library(ggplot2)     # Gráficos profesionales
library(skimr)       # EDA rápido y completo (skim())
library(GGally)      # Matriz de gráficos para variables múltiples
library(knitr)       # Tablas en Quarto
library(kableExtra)  # Tablas formateadas para informes
```

```{r}
#|label: data-load

# Carga de datos (ejemplo iris) y limpieza mínima
data("iris")
df <- as_tibble(iris) %>% 
  janitor::clean_names()   # convierte a snake_case: sepal_length, etc.

# Información básica
n_rows <- nrow(df); n_cols <- ncol(df)
tbl1<-skim(df) 
tbl1 # Resumen compacto por variable
```

```{r}
#| label: ggpairs
#| fig-cap: "Matriz de dispersión y correlación de las variables cuantitativas."
num_df <- df %>% select(where(is.numeric))
Fig1<- GGally::ggpairs(
  df,
  columns = 1:4, # solo variables numéricas
  mapping = aes(color = species), # color por especie
  upper = list(continuous = wrap("cor", size = 3)),
  diag = list(continuous = wrap("densityDiag", alpha = 0.6))
)
Fig1
```

```{r}
#| label: caja y bigotes
#| fig-cap: "Distribución de variables morfométricas en tres especies de Iris."
# Pasar el dataset a formato largo
iris_long <- df %>%
  pivot_longer(cols = -species,
               names_to = "Variable",
               values_to = "Valor")

# Gráfico unificado
Fig2 <- ggplot(iris_long, aes(x = species, y = Valor, fill = species)) +
  geom_boxplot(outlier.shape = 21, alpha = 0.7) +
  facet_wrap(~ Variable, scales = "free_y") +
  labs(
    title = "Comparación de variables morfométricas en especies de Iris",
    x = "Especies",
    y = "Valor (cm)"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "none",
    strip.text = element_text(face = "bold")
  )
Fig2

```
### Normalidad (univariada y multivariada)

```{r}
#| label: supuestos
#| fig-cap: "Evaluación de supuestos estadísticos"

# Normalidad (univariada y multivariada)
mvn_norm <- mvn(df[,1:4], mvn_test = "hz")

# Resultados
mvn_norm$univariate_normality
mvn_norm$multivariate_normality
```

